# Generated by Django 4.1.5 on 2023-01-30 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organizer',
            fields=[
                ('id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('tournament_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(default=None, max_length=100)),
                ('player_count', models.IntegerField(default=0)),
                ('format', models.CharField(default='', max_length=100)),
                ('date', models.DateTimeField(default=None)),
                ('organizer', models.ForeignKey(default=None, on_delete=django.db.models.deletion.RESTRICT, to='expert_belt_api.organizer')),
            ],
        ),
    ]
