# Generated by Django 4.1.5 on 2023-01-30 06:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("expert_belt_api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Format",
            fields=[
                (
                    "name",
                    models.CharField(
                        default=None, max_length=100, primary_key=True, serialize=False
                    ),
                ),
                ("label", models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name="tournament",
            name="game",
            field=models.CharField(
                choices=[("VGC", "Video Game Championships")],
                default="VGC",
                max_length=100,
            ),
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bio", models.TextField(blank=True, max_length=10000)),
                ("country", models.CharField(default=None, max_length=10, null=True)),
                ("birth_date", models.DateField(blank=True, null=True)),
                ("pronouns", models.CharField(default=None, max_length=255, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Record",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("wins", models.IntegerField(default=None, null=True)),
                ("losses", models.IntegerField(default=None, null=True)),
                ("ties", models.IntegerField(default=None, null=True)),
                ("drop", models.IntegerField(default=None, null=True)),
                ("placing", models.IntegerField(default=None, null=True)),
                (
                    "player",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.RESTRICT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tournament",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="expert_belt_api.tournament",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Phase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phase_number", models.IntegerField(default=1)),
                ("phase_type", models.CharField(default="SWISS", max_length=100)),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("BO1", "Best of One"),
                            ("BO3", "Best of Three"),
                            ("BO5", "Best of Five"),
                        ],
                        default="BO5",
                        max_length=3,
                    ),
                ),
                ("rounds", models.IntegerField(default=3)),
                ("final", models.BooleanField(default=False)),
                ("timer", models.BooleanField(default=None, null=True)),
                ("round_time", models.IntegerField(default=None, null=True)),
                ("auto_resolve", models.BooleanField(default=None, null=True)),
                ("check_in", models.BooleanField(default=None, null=True)),
                ("check_in_time", models.IntegerField(default=None, null=True)),
                ("bracket", models.BooleanField(default=None, null=True)),
                ("advancing_min", models.IntegerField(default=None, null=True)),
                (
                    "tournament",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="expert_belt_api.tournament",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Match",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("round", models.IntegerField()),
                (
                    "phase",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="expert_belt_api.phase",
                    ),
                ),
                (
                    "player1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="player1",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "player2",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="player2",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tournament",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="expert_belt_api.tournament",
                    ),
                ),
                (
                    "winner",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="winner",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="tournament",
            name="players",
            field=models.ManyToManyField(
                through="expert_belt_api.Record", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
